### Part 0: Installing libraries

In [1]:
%pip install spacy

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.7)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.19.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.11.9)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.12/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.8.3)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.22.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (1.17.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)

In [2]:
%pip install spacy-universal-sentence-encoder

Collecting spacy-universal-sentence-encoder
  Downloading spacy_universal_sentence_encoder-0.4.6.tar.gz (15 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tensorflow<3.0.0,>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from spacy-universal-sentence-encoder) (2.19.0)
Requirement already satisfied: spacy<4.0.0,>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy-universal-sentence-encoder) (3.8.7)
Requirement already satisfied: tensorflow-hub in /usr/local/lib/python3.12/dist-packages (from spacy-universal-sentence-encoder) (0.16.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.19.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.11.9)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.5.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.4.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (5.29.5)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (1.17.3)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (1.75.1)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.10.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.14.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.5.3)
Requirement already satisfied: tf-keras>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow-hub->spacy-universal-sentence-encoder) (2.19.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.17.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.12/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2025.8.3)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.9)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.1.3)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (1.5.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.22.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (7.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.0.3)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (1.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.1.2)
Building wheels for collected packages: spacy-universal-sentence-encoder
  Building wheel for spacy-universal-sentence-encoder (setup.py) ... done
  Created wheel for spacy-universal-sentence-encoder: filename=spacy_universal_sentence_encoder-0.4.6-py3-none-any.whl size=16541 sha256=be5afcbc41b2e64bc037031fbfd6fe760a5feb4ec0e82ba0bae727b4c16dc798
  Stored in directory: /root/.cache/pip/wheels/b8/c5/91/dc7e03329421578e554c8d2635f92fd528531123cce102c7f2
Successfully built spacy-universal-sentence-encoder
Installing collected packages: spacy-universal-sentence-encoder
Successfully installed spacy-universal-sentence-encoder-0.4.6

In [3]:
%pip install pyvis

Collecting pyvis
  Downloading pyvis-0.3.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: ipython>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from pyvis) (7.34.0)
Requirement already satisfied: jinja2>=2.9.6 in /usr/local/lib/python3.12/dist-packages (from pyvis) (3.1.6)
Requirement already satisfied: jsonpickle>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from pyvis) (4.1.1)
Requirement already satisfied: networkx>=1.11 in /usr/local/lib/python3.12/dist-packages (from pyvis) (3.5)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (75.2.0)
Collecting jedi>=0.16 (from ipython>=5.3.0->pyvis)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (4.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9.6->pyvis) (3.0.3)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=5.3.0->pyvis) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=5.3.0->pyvis) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->pyvis) (0.2.14)
Downloading pyvis-0.3.2-py3-none-any.whl (756 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.0/756.0 kB 7.8 MB/s eta 0:00:00
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 26.1 MB/s eta 0:00:00
Installing collected packages: jedi, pyvis
Successfully installed jedi-0.19.2 pyvis-0.3.2

In [4]:
%pip install geopy

Requirement already satisfied: geopy in /usr/local/lib/python3.12/dist-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /usr/local/lib/python3.12/dist-packages (from geopy) (2.1)

### Part 1: Constructing the similarity index

In order to construct the similarity index, we use spacy, in particular a universal encoder which allows for a more accurate word embedding process. This will help us in detecting true similarity, and getting rid of false-similar sentences, such as sentences that include a large amount of stop-words (e.g sentences that use "the", "a", "he", "it", etc. a lot will not appear as similar, but rather the true meaning of the sentence will be analysed).

In [5]:
import spacy
import numpy as np
import pandas as pd
import networkx as nx
import spacy_universal_sentence_encoder
from tqdm import tqdm
from google.colab import files
from pyvis.network import Network
from IPython.display import display, HTML
import folium
from geopy.geocoders import Nominatim

In [6]:
nlp = spacy_universal_sentence_encoder.load_model('en_use_lg')

Downloaded https://tfhub.dev/google/universal-sentence-encoder-large/5, Total size: 577.10MB

We read the data from the reporting frameworks table that we are working on.

In [7]:
reporting_data = pd.read_excel('ReportingFrameworks.xlsx')

In [8]:
reporting_data

,Framework,Topic,Reference,Recommendation,G_Ref,Scope,Guidance
0,TCFD,Governance,TCFD Governance A,Describe the board’s oversight of climate-rela...,TCFD Governance A1,Generic,Consider including a discussion of the followi...
1,TCFD,Governance,TCFD Governance B,Describe management’s role in assessing and ma...,TCFD Governance B1,Generic,Consider including the following information:\...
2,TCFD,Strategy,TCFD Strategy A,Describe the climate-related risks and opportu...,TCFD Strategy A1,Generic,Organisations should provide the following inf...
3,TCFD,Strategy,TCFD Strategy A,Describe the climate-related risks and opportu...,TCFD Strategy A4,Generic,Organizations should consider providing a desc...
4,TCFD,Strategy,TCFD Strategy A,Describe the climate-related risks and opportu...,TCFD Strategy A5,Banks,Banks should describe significant concentratio...
...,...,...,...,...,...,...,...
550,ESRS E4,MetricsandTargets,ESRS E4 Metrics and Targets 41,If the undertaking identified material impacts...,AR33: With regard to metrics on the extent and...,NaN,NaN
551,ESRS E4,MetricsandTargets,ESRS E4 Metrics and Targets 42,The undertaking shall disclose its anticipated...,AR39: The undertaking may include an assessmen...,NaN,NaN
552,ESRS E4,MetricsandTargets,ESRS E4 Metrics and Targets 43,The information required by paragraph 42 is in...,NaN,NaN,NaN
553,ESRS E4,MetricsandTargets,ESRS E4 Metrics and Targets 44,The objective of this Disclosure Requirement i...,NaN,NaN,NaN
554,ESRS E4,MetricsandTargets,ESRS E4 Metrics and Targets 45,The disclosure shall include:\na) a quantifica...,AR40: The quantification of the anticipated fi...,NaN,NaN

In [9]:
def similarity_finder(data, columns, run_aggregation = True):
  """
  This is a function that is calculating the similarity index between all of the entries in a specific column, using the spacy framework.

  Parameters:
  "data" represents the data that we are putting in the format provided to us by Lloyd.
  "columns" contains, in order:
  - the column which contains the framework
  - the column which contains the topic
  - the column which contains the exact reference
  - the column which contains the entry that we want to compare (which will initially be the recommendation, but may become the guidance)

  Outputs:
  The output will be similar to the similarrequrements.csv file. This output will then be fed into a download function, in case we want to download the file,
  and a networkx code which will create a network of all of these links.
  """
  framework_column = columns[0]
  topic_column = columns[1]
  reference_column = columns[2]
  comparison_column = columns[3]

  if(run_aggregation):
    data = data.replace("ESRS E1", "ESRS")
    data = data.replace("ESRS E4", "ESRS")
    data = data.replace("IFRS S1", "IFRS")
    data = data.replace("IFRS S2", "IFRS")

  n = int(len(data)*(len(data)-1)/2)
  similarity_list = []

  # Create a progress bar for the total number of comparisons, while also creating the similarity table file
  with tqdm(total=n, desc="Comparing pairs") as pbar:
    for i in range(len(data)):
      curr_framework = data.iloc[i][framework_column]
      curr_topic = data.iloc[i][topic_column]
      curr_reference = data.iloc[i][reference_column]
      curr_comparison = data.iloc[i][comparison_column]
      curr_nlp = nlp(curr_comparison)
      for j in range(i+1, len(data)):
        next_framework = data.iloc[j][framework_column]
        next_topic = data.iloc[j][topic_column]
        next_reference = data.iloc[j][reference_column]
        next_comparison = data.iloc[j][comparison_column]
        next_nlp = nlp(next_comparison)
        if (next_framework != curr_framework) and (next_topic == curr_topic): #We are getting rid of the similarities within the same framework, which are bound to be high, and we only calculate similarities where they are useful, in the same topic
          similarity_score = curr_nlp.similarity(next_nlp)
          similarity_list.append({"Topic":curr_topic, "Framework 1": curr_framework, "Reference 1": curr_reference, "Recommendation 1": curr_comparison, "Framework 2": next_framework, "Reference 2": next_reference, "Recommendation 2": next_comparison, "Similarity": similarity_score})
        pbar.update(1)  # Update the progress bar after each comparison

  similarity_table = pd.DataFrame(similarity_list)
  similarity_table.drop_duplicates(inplace=True)
  similarity_table.reset_index(drop=True, inplace=True)
  return similarity_table

In [15]:
similarity_table = similarity_finder(reporting_data, ["Framework", "Topic", "Reference", "Recommendation"])

Comparing pairs: 100%|██████████| 153735/153735 [01:10<00:00, 2175.40it/s]

In [11]:
def download_table(table, filename):
  """
  Downloads tables as a CSV file in Google Colab.

  Parameters:
  - table: pandas DataFrame to download
  - filename: name of the file to save (without extension)

  """
  # Save the DataFrame to a CSV file
  table.to_csv(filename, index=False)

  # Download the file
  files.download(filename)

  print(f"File '{filename}' has been downloaded!")

In [ ]:
download_table(similarity_table, "similarity_table.csv")

File 'similarity_table.csv' has been downloaded!

### Part 2: Constructing the network of similarity

Below, what we will be creating is a similarity metric between different frameworks. The list of topics from which one can choose below is as follows: Disclosure, Governance, Metrics and Targets, Risk Management and Strategy.

In [12]:
def similarity_network_table(original_list = ["Disclosure", "Governance", "MetricsandTargets", "RiskManagement", "Strategy"], original_data=similarity_table):
  """
  This is a function that is calculating the data required to build a network of the similarities of different frameworks, based on a list of topics.

  Parameters:
  "list" is the list of topics on which we want to base the similarity. It can contain all topics, but it must include at least one. It's originally defined as the list of all topics.
  "data" is the underlying data, which in this file should be the similarity table found before. It's originally defined as the similarity_table. We are assuming that the data is in the format of the similarity table.

  Outputs:
  A table containing the similarity between all of the frameworks, based on the list of topics. This similarity is calculated as the average of the similarities of all recommendations
  in the chosen topics.
  """
  filtered_data = original_data.copy()
  for i in range(len(filtered_data)):
    if not(filtered_data["Topic"][i] in original_list):
      filtered_data.drop(i, inplace=True)
  filtered_data.reset_index(drop=True, inplace=True)
  framework_1 = pd.unique(filtered_data["Framework 1"])
  framework_2 = pd.unique(filtered_data["Framework 2"])
  all_frameworks = np.concatenate((framework_1, framework_2))
  all_frameworks = pd.unique(all_frameworks)
  similarity_list = []
  with tqdm(total=len(all_frameworks)*(len(all_frameworks)-1)/2, desc="Comparing pairs") as pbar:
    for i in range(len(all_frameworks)):
      curr_framework = all_frameworks[i]
      for j in range(i+1,len(all_frameworks)):
        next_framework = all_frameworks[j]
        similarity = filtered_data.loc[(filtered_data["Framework 1"] == curr_framework) & (filtered_data["Framework 2"] == next_framework)]["Similarity"].mean()
        similarity_list.append({"Framework 1": curr_framework, "Framework 2": next_framework, "Similarity": similarity})
        pbar.update(1)

  similarity_network = pd.DataFrame(similarity_list)
  similarity_network.fillna(0, inplace=True)
  similarity_network.drop_duplicates(inplace=True)
  similarity_network.reset_index(drop=True, inplace=True)
  return similarity_network

In [13]:
similarity_network_table_all_metrics = similarity_network_table()
similarity_network_table_disclosure = similarity_network_table(["Disclosure"])
similarity_network_table_governance = similarity_network_table(["Governance"])
similarity_network_table_metrics = similarity_network_table(["MetricsandTargets"])
similarity_network_table_risk = similarity_network_table(["RiskManagement"])
similarity_network_table_strategy = similarity_network_table(["Strategy"])

Comparing pairs: 100%|██████████| 28/28.0 [00:00<00:00, 928.66it/s]
Comparing pairs: 100%|██████████| 3/3.0 [00:00<00:00, 779.61it/s]
Comparing pairs: 100%|██████████| 21/21.0 [00:00<00:00, 1443.09it/s]
Comparing pairs: 0it [00:00, ?it/s]
Comparing pairs: 0it [00:00, ?it/s]
Comparing pairs: 100%|██████████| 15/15.0 [00:00<00:00, 1060.38it/s]

In [16]:
similarity_table

,Topic,Framework 1,Reference 1,Recommendation 1,Framework 2,Reference 2,Recommendation 2,Similarity
0,Governance,TCFD,TCFD Governance A,Describe the board’s oversight of climate-rela...,TNFD,TNFD Governance A,Describe the board’s oversight of naturerelate...,0.861571
1,Governance,TCFD,TCFD Governance A,Describe the board’s oversight of climate-rela...,TNFD,TNFD Governance B,Describe management’s role in assessing and ma...,0.669910
2,Governance,TCFD,TCFD Governance A,Describe the board’s oversight of climate-rela...,TNFD,TNFD Governance C,Describe the organisation’s human rights polic...,0.429584
3,Governance,TCFD,TCFD Governance A,Describe the board’s oversight of climate-rela...,IFRS,IFRS S1 26,The objective of sustainability-related financ...,0.268225
4,Governance,TCFD,TCFD Governance A,Describe the board’s oversight of climate-rela...,IFRS,IFRS S1 27,"To achieve this objective, an entity shall dis...",0.210691
...,...,...,...,...,...,...,...,...
4797,Disclosure,MAS,MAS Disclosure 7.3,The insurer should review its disclosure regul...,ESRS,ESRS E1 Disclosure 113,The undertaking shall include in its sustainab...,0.130172
4798,Disclosure,MAS,MAS Disclosure 7.3,The insurer should review its disclosure regul...,ESRS,ESRS E1 Disclosure 114,When the undertaking includes in its sustainab...,0.211078
4799,Disclosure,MAS,MAS Disclosure 7.3,The insurer should review its disclosure regul...,ESRS,ESRS E1 Disclosure 115,The undertaking shall structure its sustainabi...,0.136216
4800,Disclosure,MAS,MAS Disclosure 7.3,The insurer should review its disclosure regul...,ESRS,ESRS E1 Disclosure 116,The disclosures required by sector-specific ES...,0.261648
4801,Disclosure,MAS,MAS Disclosure 7.3,The insurer should review its disclosure regul...,ESRS,ESRS E1 Disclosure 117,Where the undertaking develops material entity...,0.189906

We are now going to asign to each framework a country where it either originated from or is in use.

In [17]:
download_table(similarity_network_table_all_metrics, "similarity_network_table_all_metrics.csv")
download_table(similarity_network_table_disclosure, "similarity_network_table_disclosure.csv")
download_table(similarity_network_table_governance, "similarity_network_table_governance.csv")
download_table(similarity_network_table_metrics, "similarity_network_table_metrics.csv")
download_table(similarity_network_table_risk, "similarity_network_table_risk.csv")
download_table(similarity_network_table_strategy, "similarity_network_table_strategy.csv")

File 'similarity_network_table_all_metrics.csv' has been downloaded!

File 'similarity_network_table_disclosure.csv' has been downloaded!

File 'similarity_network_table_governance.csv' has been downloaded!

File 'similarity_network_table_metrics.csv' has been downloaded!

File 'similarity_network_table_risk.csv' has been downloaded!

File 'similarity_network_table_strategy.csv' has been downloaded!

### Map of regulations and adopting countries

In [ ]:
adoption_dict = {
    "Frameworks":["TCFD", "TNFD", "PRA", "IFRS", "TPT", "BMA", "MAS", "ESRS"],
    "Countries":[["Canada", "France", "Germany", "Italy", "Japan", "United Kingdom", "USA", "New Zealand", "Switzerland", "Singapore", "Brazil", "China", "South Africa"],
                 ["Brazil", "China", "Colombia", "Costa Rica", "Egypt", "India", "Indonesia", "Kenya", "Malaysia", "Mexico", "Morocco", "Nigeria", "Peru", "Philippines", "South Africa"],
                 ["United Kingdom"],
                 ["Turkey", "Bangladesh", "Brazil", "Australia", "Japan", "United Kingdom", "Canada", "Singapore", "New Zealand", "Nigeria", "South Africa", "Malaysia", "China"],
                 ["United Kingdom"],
                 ["Bermuda"],
                 ["Singapore"],
                 ["Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden"]]
}