### Part 0: Installing libraries

In [1]:
%pip install spacy

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.11.12)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.0.1)

In [2]:
%pip install spacy-universal-sentence-encoder

Collecting spacy-universal-sentence-encoder
  Downloading spacy_universal_sentence_encoder-0.4.6.tar.gz (15 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tensorflow<3.0.0,>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from spacy-universal-sentence-encoder) (2.19.0)
Requirement already satisfied: spacy<4.0.0,>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy-universal-sentence-encoder) (3.8.11)
Requirement already satisfied: tensorflow-hub in /usr/local/lib/python3.12/dist-packages (from spacy-universal-sentence-encoder) (0.16.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (25.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.4.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (5.29.5)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (2.0.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (1.76.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.10.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.5.4)
Requirement already satisfied: tf-keras>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow-hub->spacy-universal-sentence-encoder) (2.19.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.18.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (2025.11.12)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.10)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (3.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (8.3.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (7.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy<4.0.0,>=3.0.0->spacy-universal-sentence-encoder) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow<3.0.0,>=2.4.0->spacy-universal-sentence-encoder) (0.1.2)
Building wheels for collected packages: spacy-universal-sentence-encoder
  Building wheel for spacy-universal-sentence-encoder (setup.py) ... done
  Created wheel for spacy-universal-sentence-encoder: filename=spacy_universal_sentence_encoder-0.4.6-py3-none-any.whl size=16541 sha256=88b2b2ab73f45cd81777828d19739451043a79356a87731929b64f952ff2ccf7
  Stored in directory: /root/.cache/pip/wheels/b8/c5/91/dc7e03329421578e554c8d2635f92fd528531123cce102c7f2
Successfully built spacy-universal-sentence-encoder
Installing collected packages: spacy-universal-sentence-encoder
Successfully installed spacy-universal-sentence-encoder-0.4.6

In [3]:
%pip install pyvis

Collecting pyvis
  Downloading pyvis-0.3.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: ipython>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from pyvis) (7.34.0)
Requirement already satisfied: jinja2>=2.9.6 in /usr/local/lib/python3.12/dist-packages (from pyvis) (3.1.6)
Requirement already satisfied: jsonpickle>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from pyvis) (4.1.1)
Requirement already satisfied: networkx>=1.11 in /usr/local/lib/python3.12/dist-packages (from pyvis) (3.6.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (75.2.0)
Collecting jedi>=0.16 (from ipython>=5.3.0->pyvis)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=5.3.0->pyvis) (4.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9.6->pyvis) (3.0.3)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=5.3.0->pyvis) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=5.3.0->pyvis) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->pyvis) (0.2.14)
Downloading pyvis-0.3.2-py3-none-any.whl (756 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.0/756.0 kB 15.6 MB/s eta 0:00:00
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 46.5 MB/s eta 0:00:00
Installing collected packages: jedi, pyvis
Successfully installed jedi-0.19.2 pyvis-0.3.2

In [4]:
%pip install geopy

Requirement already satisfied: geopy in /usr/local/lib/python3.12/dist-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /usr/local/lib/python3.12/dist-packages (from geopy) (2.1)

### Part 1: Constructing the similarity index

In order to construct the similarity index, we use spacy, in particular a universal encoder which allows for a more accurate word embedding process. This will help us in detecting true similarity, and getting rid of false-similar sentences, such as sentences that include a large amount of stop-words (e.g sentences that use "the", "a", "he", "it", etc. a lot will not appear as similar, but rather the true meaning of the sentence will be analysed).

In [5]:
import spacy
import numpy as np
import pandas as pd
import networkx as nx
import spacy_universal_sentence_encoder
from tqdm import tqdm
from google.colab import files
from pyvis.network import Network
from IPython.display import display, HTML
import folium
from geopy.geocoders import Nominatim

In [6]:
nlp = spacy_universal_sentence_encoder.load_model('en_use_lg')

Downloaded https://tfhub.dev/google/universal-sentence-encoder-large/5, Total size: 577.10MB

We read the data from the reporting frameworks table that we are working on.

In [26]:
reporting_data = pd.read_excel('ReportingFrameworks.xlsx')

In [27]:
reporting_data

,Framework,Topic,Reference,Recommendation,G_Ref,Scope,Guidance
0,TCFD,Governance,TCFD Governance A,Describe the board’s oversight of climate-rela...,TCFD Governance A1,Generic,Consider including a discussion of the followi...
1,TCFD,Governance,TCFD Governance B,Describe management’s role in assessing and ma...,TCFD Governance B1,Generic,Consider including the following information:\...
2,TCFD,Strategy,TCFD Strategy A,Describe the climate-related risks and opportu...,TCFD Strategy A1,Generic,Organisations should provide the following inf...
3,TCFD,Strategy,TCFD Strategy A,Describe the climate-related risks and opportu...,TCFD Strategy A4,Generic,Organizations should consider providing a desc...
4,TCFD,Strategy,TCFD Strategy A,Describe the climate-related risks and opportu...,TCFD Strategy A5,Banks,Banks should describe significant concentratio...
...,...,...,...,...,...,...,...
695,SBTi,MetricsandTargets,FINZ-C19 C19.1,"Financial institutions shall adhere, at all ti...",NaN,Financial Institutions,SBTi CLAIMS
696,SBTi,MetricsandTargets,FINZ-C19 C19.2,Claims made by financial institutions shall ac...,NaN,Financial Institutions,SBTi CLAIMS
697,SBTi,MetricsandTargets,FINZ-C19 C19.3,Financial institutions shall ensure that all c...,NaN,Financial Institutions,SBTi CLAIMS
698,SBTi,MetricsandTargets,FINZ-C19 C19.4,All claim content shall be fully substantiated...,NaN,Financial Institutions,SBTi CLAIMS
699,SBTi,MetricsandTargets,FINZ-C19 R19.1,The ISEAL Sustainability Claims Good Practice ...,NaN,Financial Institutions,SBTi CLAIMS

In [28]:
def similarity_finder(data, columns, run_aggregation = True):
  """
  This is a function that is calculating the similarity index between all of the entries in a specific column, using the spacy framework.

  Parameters:
  "data" represents the data that we are putting in the format provided to us by Lloyd.
  "columns" contains, in order:
  - the column which contains the framework
  - the column which contains the topic
  - the column which contains the exact reference
  - the column which contains the entry that we want to compare (which will initially be the recommendation, but may become the guidance)

  Outputs:
  The output will be similar to the similarrequrements.csv file. This output will then be fed into a download function, in case we want to download the file,
  and a networkx code which will create a network of all of these links.
  """
  framework_column = columns[0]
  topic_column = columns[1]
  reference_column = columns[2]
  comparison_column = columns[3]

  if(run_aggregation):
    data = data.replace("ESRS E1", "ESRS")
    data = data.replace("ESRS E4", "ESRS")
    data = data.replace("IFRS S1", "IFRS")
    data = data.replace("IFRS S2", "IFRS")

  n = int(len(data)*(len(data)-1)/2)
  similarity_list = []

  # Create a progress bar for the total number of comparisons, while also creating the similarity table file
  with tqdm(total=n, desc="Comparing pairs") as pbar:
    for i in range(len(data)):
      curr_framework = data.iloc[i][framework_column]
      curr_topic = data.iloc[i][topic_column]
      curr_reference = data.iloc[i][reference_column]
      curr_comparison = data.iloc[i][comparison_column]
      curr_nlp = nlp(curr_comparison)
      for j in range(i+1, len(data)):
        next_framework = data.iloc[j][framework_column]
        next_topic = data.iloc[j][topic_column]
        next_reference = data.iloc[j][reference_column]
        next_comparison = data.iloc[j][comparison_column]
        next_nlp = nlp(next_comparison)
        if (next_framework != curr_framework) and (next_topic == curr_topic): #We are getting rid of the similarities within the same framework, which are bound to be high, and we only calculate similarities where they are useful, in the same topic
          similarity_score = curr_nlp.similarity(next_nlp)
          similarity_list.append({"Topic":curr_topic, "Framework 1": curr_framework, "Reference 1": curr_reference, "Recommendation 1": curr_comparison, "Framework 2": next_framework, "Reference 2": next_reference, "Recommendation 2": next_comparison, "Similarity": similarity_score})
        pbar.update(1)  # Update the progress bar after each comparison

  similarity_table = pd.DataFrame(similarity_list)
  similarity_table.drop_duplicates(inplace=True)
  similarity_table.reset_index(drop=True, inplace=True)
  return similarity_table

In [29]:
similarity_table = similarity_finder(reporting_data, ["Framework", "Topic", "Reference", "Recommendation"])

Comparing pairs: 100%|██████████| 244650/244650 [01:52<00:00, 2171.10it/s]

In [30]:
def download_table(table, filename):
  """
  Downloads tables as a CSV file in Google Colab.

  Parameters:
  - table: pandas DataFrame to download
  - filename: name of the file to save (without extension)

  """
  # Save the DataFrame to a CSV file
  table.to_csv(filename, index=False)

  # Download the file
  files.download(filename)

  print(f"File '{filename}' has been downloaded!")

In [12]:
download_table(similarity_table, "similarity_table.csv")

File 'similarity_table.csv' has been downloaded!

### Part 2: Constructing the network of similarity

Below, what we will be creating is a similarity metric between different frameworks. The list of topics from which one can choose below is as follows: Disclosure, Governance, Metrics and Targets, Risk Management and Strategy.

In [31]:
def similarity_network_table(original_list = ["Disclosure", "Governance", "MetricsandTargets", "RiskManagement", "Strategy"], original_data=similarity_table):
  """
  This is a function that is calculating the data required to build a network of the similarities of different frameworks, based on a list of topics.

  Parameters:
  "list" is the list of topics on which we want to base the similarity. It can contain all topics, but it must include at least one. It's originally defined as the list of all topics.
  "data" is the underlying data, which in this file should be the similarity table found before. It's originally defined as the similarity_table. We are assuming that the data is in the format of the similarity table.

  Outputs:
  A table containing the similarity between all of the frameworks, based on the list of topics. This similarity is calculated as the average of the similarities of all recommendations
  in the chosen topics.
  """
  filtered_data = original_data.copy()
  for i in range(len(filtered_data)):
    if not(filtered_data["Topic"][i] in original_list):
      filtered_data.drop(i, inplace=True)
  filtered_data.reset_index(drop=True, inplace=True)
  framework_1 = pd.unique(filtered_data["Framework 1"])
  framework_2 = pd.unique(filtered_data["Framework 2"])
  all_frameworks = np.concatenate((framework_1, framework_2))
  all_frameworks = pd.unique(all_frameworks)
  similarity_list = []
  with tqdm(total=len(all_frameworks)*(len(all_frameworks)-1)/2, desc="Comparing pairs") as pbar:
    for i in range(len(all_frameworks)):
      curr_framework = all_frameworks[i]
      for j in range(i+1,len(all_frameworks)):
        next_framework = all_frameworks[j]
        similarity = filtered_data.loc[(filtered_data["Framework 1"] == curr_framework) & (filtered_data["Framework 2"] == next_framework)]["Similarity"].mean()
        similarity_list.append({"Framework 1": curr_framework, "Framework 2": next_framework, "Similarity": similarity})
        pbar.update(1)

  similarity_network = pd.DataFrame(similarity_list)
  similarity_network.fillna(0, inplace=True)
  similarity_network.drop_duplicates(inplace=True)
  similarity_network.reset_index(drop=True, inplace=True)
  return similarity_network

In [32]:
similarity_network_table_all_metrics = similarity_network_table()
similarity_network_table_disclosure = similarity_network_table(["Disclosure"])
similarity_network_table_governance = similarity_network_table(["Governance"])
similarity_network_table_metrics = similarity_network_table(["MetricsandTargets"])
similarity_network_table_risk = similarity_network_table(["RiskManagement"])
similarity_network_table_strategy = similarity_network_table(["Strategy"])

Comparing pairs: 100%|██████████| 45/45.0 [00:00<00:00, 338.75it/s]
Comparing pairs: 100%|██████████| 10/10.0 [00:00<00:00, 1017.44it/s]
Comparing pairs: 100%|██████████| 36/36.0 [00:00<00:00, 1255.41it/s]
Comparing pairs: 100%|██████████| 6/6.0 [00:00<00:00, 461.53it/s]
Comparing pairs: 100%|██████████| 28/28.0 [00:00<00:00, 717.44it/s]
Comparing pairs: 100%|██████████| 15/15.0 [00:00<00:00, 781.64it/s]

In [33]:
similarity_table

,Topic,Framework 1,Reference 1,Recommendation 1,Framework 2,Reference 2,Recommendation 2,Similarity
0,Governance,TCFD,TCFD Governance A,Describe the board’s oversight of climate-rela...,TNFD,TNFD Governance A,Describe the board’s oversight of naturerelate...,0.861571
1,Governance,TCFD,TCFD Governance A,Describe the board’s oversight of climate-rela...,TNFD,TNFD Governance B,Describe management’s role in assessing and ma...,0.669910
2,Governance,TCFD,TCFD Governance A,Describe the board’s oversight of climate-rela...,TNFD,TNFD Governance C,Describe the organisation’s human rights polic...,0.429584
3,Governance,TCFD,TCFD Governance A,Describe the board’s oversight of climate-rela...,IFRS,IFRS S1 26,The objective of sustainability-related financ...,0.268225
4,Governance,TCFD,TCFD Governance A,Describe the board’s oversight of climate-rela...,IFRS,IFRS S1 27,"To achieve this objective, an entity shall dis...",0.210691
...,...,...,...,...,...,...,...,...
11139,Disclosure,OSFI,OSFI Chapter 2 Principle 6,The company should disclose information consis...,SBTi,FINZ-C17 C17.1,Financial institutions shall commit to separat...,0.115417
11140,Disclosure,OSFI,OSFI Chapter 2 Principle 6,The company should disclose information consis...,SBTi,FINZ-C17 C17.2,Financial institutions shall commit to startin...,0.169681
11141,Disclosure,OSFI,OSFI Chapter 2 Principle 6,The company should disclose information consis...,SBTi,FINZ-C17 R17.1,Financial institutions should annually and pub...,0.191425
11142,Disclosure,OSFI,OSFI Chapter 2 Principle 6,The company should disclose information consis...,SBTi,FINZ-C17 R17.2,Financial institutions should use data with th...,0.257425
11143,Disclosure,OSFI,OSFI Chapter 2 Principle 6,The company should disclose information consis...,SBTi,FINZ-C17 R17.3,For the climate-alignment and sector metric as...,0.078844

We are now going to asign to each framework a country where it either originated from or is in use.

In [34]:
download_table(similarity_network_table_all_metrics, "similarity_network_table_all_metrics.csv")
download_table(similarity_network_table_disclosure, "similarity_network_table_disclosure.csv")
download_table(similarity_network_table_governance, "similarity_network_table_governance.csv")
download_table(similarity_network_table_metrics, "similarity_network_table_metrics.csv")
download_table(similarity_network_table_risk, "similarity_network_table_risk.csv")
download_table(similarity_network_table_strategy, "similarity_network_table_strategy.csv")

File 'similarity_network_table_all_metrics.csv' has been downloaded!

File 'similarity_network_table_disclosure.csv' has been downloaded!

File 'similarity_network_table_governance.csv' has been downloaded!

File 'similarity_network_table_metrics.csv' has been downloaded!

File 'similarity_network_table_risk.csv' has been downloaded!

File 'similarity_network_table_strategy.csv' has been downloaded!

### Map of regulations and adopting countries

In [16]:
adoption_dict = {
    "Frameworks":["TCFD", "TNFD", "PRA", "IFRS", "TPT", "BMA", "MAS", "ESRS", "OSFI", "SBTI"],
    "Countries":[["Canada", "France", "Germany", "Italy", "Japan", "United Kingdom", "USA", "New Zealand", "Switzerland", "Singapore", "Brazil", "China", "South Africa"],
                 ["Brazil", "China", "Colombia", "Costa Rica", "Egypt", "India", "Indonesia", "Kenya", "Malaysia", "Mexico", "Morocco", "Nigeria", "Peru", "Philippines", "South Africa"],
                 ["United Kingdom"],
                 ["Turkey", "Bangladesh", "Brazil", "Australia", "Japan", "United Kingdom", "Canada", "Singapore", "New Zealand", "Nigeria", "South Africa", "Malaysia", "China"],
                 ["United Kingdom"],
                 ["Bermuda"],
                 ["Singapore"],
                 ["Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden"],
                 ["Canada"],
                 ["Japan", "United Kingdom", "USA", "China", "Germany", "France", "India", "Italy", "Canada", "South Korea", "Mexico", "Brazil", "Australia", "South Africa", "Turkey", "Romania", "Malta"]]
}

## Framework comparison tool

In [35]:
pip install PyMuPDF

Collecting PyMuPDF
  Downloading pymupdf-1.26.7-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (3.4 kB)
Downloading pymupdf-1.26.7-cp310-abi3-manylinux_2_28_x86_64.whl (24.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 28.3 MB/s eta 0:00:00
Installing collected packages: PyMuPDF
Successfully installed PyMuPDF-1.26.7

In [36]:
import pymupdf

In [54]:
doc = pymupdf.open("climate-transition-plan-2024.pdf")

In [59]:
paragraph_list = []
text_list = []
for page in doc: # iterate the document pages
  text = page.get_text() # get plain text encoded as UTF-8
  text_list.append(text)
text_list = [text.replace('\n', ' ') for text in text_list]

page 0 of climate-transition-plan-2024.pdf
page 1 of climate-transition-plan-2024.pdf
page 2 of climate-transition-plan-2024.pdf
page 3 of climate-transition-plan-2024.pdf
page 4 of climate-transition-plan-2024.pdf
page 5 of climate-transition-plan-2024.pdf
page 6 of climate-transition-plan-2024.pdf
page 7 of climate-transition-plan-2024.pdf
page 8 of climate-transition-plan-2024.pdf
page 9 of climate-transition-plan-2024.pdf
page 10 of climate-transition-plan-2024.pdf
page 11 of climate-transition-plan-2024.pdf
page 12 of climate-transition-plan-2024.pdf
page 13 of climate-transition-plan-2024.pdf
page 14 of climate-transition-plan-2024.pdf
page 15 of climate-transition-plan-2024.pdf
page 16 of climate-transition-plan-2024.pdf
page 17 of climate-transition-plan-2024.pdf
page 18 of climate-transition-plan-2024.pdf
page 19 of climate-transition-plan-2024.pdf
page 20 of climate-transition-plan-2024.pdf
page 21 of climate-transition-plan-2024.pdf
page 22 of climate-transition-plan-2024.pdf
page 23 of climate-transition-plan-2024.pdf
page 24 of climate-transition-plan-2024.pdf

In [68]:
text_data_frame=pd.DataFrame(text_list)
text_data_frame.columns=["Paragraph"]

In [76]:
def document_similarity(data, document, columns, run_aggregation = True):
  """
  This is a function that is calculating the similarity index between all of the entries in two documents, using the spacy framework.

  Parameters:
  "data" represents the data that we are putting in the format provided to us by Lloyd, aka the ReportingFrameworks.xlsx doc
  "columns" contains, in order:
  - the column which contains the framework
  - the column which contains the topic
  - the column which contains the exact reference
  - the column which contains the entry that we want to compare (which will initially be the recommendation, but may become the guidance)
  "document" represents the data extracted, page by page, from the pdf document provided

  Outputs:
  The output will be similar to the similarrequrements.csv file. This output will then be fed into a download function, in case we want to download the file,
  and a networkx code which will create a network of all of these links.
  """
  framework_column = columns[0]
  topic_column = columns[1]
  reference_column = columns[2]
  comparison_column = columns[3]

  if(run_aggregation):
    data = data.replace("ESRS E1", "ESRS")
    data = data.replace("ESRS E4", "ESRS")
    data = data.replace("IFRS S1", "IFRS")
    data = data.replace("IFRS S2", "IFRS")

  n = int(len(data)*len(document))
  similarity_list = []


  for i in range(len(data)):
    curr_framework = data.iloc[i][framework_column]
    curr_topic = data.iloc[i][topic_column]
    curr_reference = data.iloc[i][reference_column]
    curr_comparison = data.iloc[i][comparison_column]
    curr_nlp = nlp(curr_comparison)
    for j in range(len(document)):
      doc_comparison = document.iloc[j]['Paragraph'] # Fixed: Changed data.iloc[j] to document.iloc[j]
      doc_nlp = nlp(doc_comparison)
      similarity_score = curr_nlp.similarity(doc_nlp)
      similarity_list.append({"Topic":curr_topic, "Framework": curr_framework, "Reference": curr_reference, "Recommendation": curr_comparison, "Document page": doc_comparison, "Similarity": similarity_score})

  similarity_table = pd.DataFrame(similarity_list)
  similarity_table.drop_duplicates(inplace=True)
  similarity_table.reset_index(drop=True, inplace=True)

  #Calculating the similarity for each table for each topic
  similarity_network_list = []
  all_frameworks = pd.unique(similarity_table["Framework"])
  for i in range(len(all_frameworks)):
    curr_framework = all_frameworks[i]
    curr_framework_data = similarity_table.loc[similarity_table["Framework"] == curr_framework]
    curr_framework_data.reset_index(drop=True, inplace=True)
    all_topics = pd.unique(curr_framework_data["Topic"])
    for j in range(len(all_topics)):
      curr_topic = all_topics[j]
      curr_topic_data = curr_framework_data.loc[curr_framework_data["Topic"] == curr_topic]
      curr_topic_data.reset_index(drop=True, inplace=True)
      similarity = curr_topic_data["Similarity"].mean()
      similarity_network_list.append({"Framework": curr_framework, "Topic": curr_topic, "Similarity": similarity})
    similarity_network_list.append({"Framework": curr_framework, "Topic":"Overall", "Similarity":curr_framework_data["Similarity"].mean()})

  similarity_network = pd.DataFrame(similarity_network_list)
  similarity_network.fillna(0, inplace=True)
  similarity_network.drop_duplicates(inplace=True)

  return similarity_network

In [77]:
sim_table = document_similarity(reporting_data, text_data_frame, ["Framework", "Topic", "Reference", "Recommendation"])

In [78]:
sim_table

   Framework                  Topic  Similarity
0       TCFD             Governance    0.076484
1       TCFD               Strategy    0.119560
2       TCFD         RiskManagement    0.053880
3       TCFD      MetricsandTargets    0.090671
4       TCFD                Overall    0.085937
5       TNFD             Governance    0.110009
6       TNFD               Strategy    0.134484
7       TNFD         RiskManagement    0.096288
8       TNFD      MetricsandTargets    0.073423
9       TNFD                Overall    0.105242
10       PRA               Strategy    0.266618
11       PRA         RiskManagement    0.190803
12       PRA       ScenarioAnalysis    0.247214
13       PRA             Disclosure    0.109491
14       PRA                Overall    0.193019
15      IFRS             Governance    0.261296
16      IFRS               Strategy    0.165577
17      IFRS         RiskManagement    0.209207
18      IFRS      Metricsandtargets    0.088765
19      IFRS    GeneralRequirements    0.067819
20      IFRS                Overall    0.110025
21       TPT               Strategy    0.106048
22       TPT      Metricsandtargets    0.072559
23       TPT             Governance    0.050788
24       TPT                Overall    0.084455
25       BMA  MaterialityAssessment    0.204177
26       BMA             Governance    0.166722
27       BMA         RiskManagement    0.260395
28       BMA                   ORSA    0.222366
29       BMA                Overall    0.230095
30       MAS             Governance    0.279870
31       MAS         RiskManagement    0.185417
32       MAS           Underwriting    0.236845
33       MAS             Investment    0.157664
34       MAS             Disclosure    0.137259
35       MAS                Overall    0.192711
36      ESRS             Governance    0.086874
37      ESRS               Strategy    0.209875
38      ESRS         RiskManagement    0.169613
39      ESRS      MetricsandTargets    0.121565
40      ESRS             Disclosure    0.071986
41      ESRS                Overall    0.120269
42      OSFI             Governance    0.136561
43      OSFI         RiskManagement    0.044371
44      OSFI       ScenarioAnalysis    0.132951
45      OSFI                   ORSA    0.050020
46      OSFI             Disclosure   -0.019653
47      OSFI                Overall    0.034777
48      SBTi      MetricsandTargets    0.090728
49      SBTi             Governance    0.096234
50      SBTi             Disclosure    0.065172
51      SBTi                Overall    0.088762